wandb_version: 1

B1:
  desc: null
  value: 1
B2:
  desc: null
  value: 1
LR:
  desc: null
  value: 0.001
N_SIDE_LAYER:
  desc: null
  value: 8
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708438664.141917
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 9
      - 55
      - 103
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
