method: bayes
metric:
  goal: minimize
  name: Wall Time
parameters:
  B1:
    distribution: int_uniform
    max: 80
    min: 9
  B2:
    distribution: int_uniform
    max: 4
    min: 1
  B3:
    distribution: uniform
    max: 0.4809927450543069
    min: 0.05279516477003922
  B4:
    distribution: int_uniform
    max: 32
    min: 5
  B5:
    distribution: int_uniform
    max: 4
    min: 1
  N_SIDE_LAYER:
    distribution: int_uniform
    max: 12
    min: 4
program: train.py